import Head from 'next/head'
import Header from "../components/Header"
import { Inter } from '@next/font/google'
import Community from '@/components/Community'
import Stat from '@/components/Stat'
import Guide from '@/components/Guide'
import Footer from '@/components/Footer'
import Banner from '@/components/Banner'


export default function Home(data) {
  return (
    <>
    <Head>
        <title>Elon Giveaway</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <Header price = {data.data[0]}/>

    <main className='main'>
      <Banner/>
      <Community/>
      <Stat data = {data.data[0]}/>
      <Guide/>
    </main>

    <Footer/>
    </>
  )
}


export async function getServerSideProps({req, res}) {
  res.setHeader(
    'Cache-Control',
    'public, s-maxage=10, stale-while-revalidate=59'
  )
  req = await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=bitcoin&order=market_cap_desc&per_page=100&page=1&sparkline=false')
  const data = await req.json()
  return {
    props: { data}, // will be passed to the page component as props
  }
}